name: Node CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  Evaluator:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      
      - name: Instalação das dependências
        run: cd Back-end && npm ci

      - name: Rodando ESlint
        run: cd Back-end && npm run lint