name: Node CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  Avaliation:

    runs-on: ubuntu-latest

    steps:
      -uses: action/checkout@v3
      -name: Use Node.js
       uses: actions/setup-node@v3
       with:
        node-version: 14
      
      -name: Instalação das dependências
       run: npm ci

      -name: Rodando ESlint
       run: npm run lint